//
//  Sound.swift
//
//  Created by 63rabbits goodman on 2024/02/27.
//

import AudioToolbox

class SoundID {

    static let Vibration_longStrong = SystemSoundID(kSystemSoundID_Vibrate)

//    enum ID: SystemSoundID, CaseIterable {
    enum ID: SystemSoundID {
//                                                                                          SystemSoundID      File Name (caf : Core Audio Format)
                                case ringback_tone_ansi_caf                             =   30              // ringback_tone_ansi.caf
                                case ringback_tone_cept_caf                             =   31              // ringback_tone_cept.caf
                                case busy_tone_ansi_caf                                 =   32              // busy_tone_ansi.caf
                                case busy_tone_cept_caf                                 =   33              // busy_tone_cept.caf
                                case call_waiting_tone_ansi_caf                         =   34              // call_waiting_tone_ansi.caf
                                case call_waiting_tone_cept_caf                         =   35              // call_waiting_tone_cept.caf
                                case end_call_tone_cept_caf                             =   36              // end_call_tone_cept.caf
                                case ringback_tone_hk_caf                               =   37              // ringback_tone_hk.caf
                                case ringback_tone_aus_caf                              =   38              // ringback_tone_aus.caf
                                case ringback_tone_uk_caf                               =   39              // ringback_tone_uk.caf
                                case new_mail_caf                                       =   1000            // new-mail.caf
                                case mail_sent_caf                                      =   1001            // mail-sent.caf
                                case sms_received1_caf                                  =   1002            // sms-received1.caf
                                case ReceivedMessage_caf                                =   1003            // ReceivedMessage.caf
                                case SentMessage_caf                                    =   1004            // SentMessage.caf
                                case alarm_caf                                          =   1005            // alarm.caf
                                case low_power_caf                                      =   1006            // low_power.caf
                                case sms_received1_caf_02                               =   1007            // sms-received1.caf
                                case sms_received2_caf                                  =   1008            // sms-received2.caf
                                case sms_received3_caf                                  =   1009            // sms-received3.caf
                                case sms_received4_caf                                  =   1010            // sms-received4.caf
                                case sms_received1_caf_03                               =   1012            // sms-received1.caf
                                case sms_received5_caf                                  =   1013            // sms-received5.caf
                                case sms_received6_caf                                  =   1014            // sms-received6.caf
                                case sms_received1_caf_04                               =   1015            // sms-received1.caf
                                case tweet_sent_caf                                     =   1016            // tweet_sent.caf
                                case alarm_caf_02                                       =   1017            // alarm.caf
                                case Swish_caf                                          =   1018            // Swish.caf
                                case Anticipate_caf                                     =   1020            // Anticipate.caf
                                case Bloom_caf                                          =   1021            // Bloom.caf
                                case Calypso_caf                                        =   1022            // Calypso.caf
                                case Choo_Choo_caf                                      =   1023            // Choo_Choo.caf
                                case Descent_caf                                        =   1024            // Descent.caf
                                case Fanfare_caf                                        =   1025            // Fanfare.caf
                                case Ladder_caf                                         =   1026            // Ladder.caf
                                case Minuet_caf                                         =   1027            // Minuet.caf
                                case News_Flash_caf                                     =   1028            // News_Flash.caf
                                case Noir_caf                                           =   1029            // Noir.caf
                                case Sherwood_Forest_caf                                =   1030            // Sherwood_Forest.caf
                                case Spell_caf                                          =   1031            // Spell.caf
                                case Suspense_caf                                       =   1032            // Suspense.caf
                                case Telegraph_caf                                      =   1033            // Telegraph.caf
                                case Tiptoes_caf                                        =   1034            // Tiptoes.caf
                                case Typewriters_caf                                    =   1035            // Typewriters.caf
                                case Update_caf                                         =   1036            // Update.caf
                                case ussd_caf                                           =   1050            // ussd.caf
                                case SIMToolkitCallDropped_caf                          =   1051            // SIMToolkitCallDropped.caf
                                case SIMToolkitGeneralBeep_caf                          =   1052            // SIMToolkitGeneralBeep.caf
                                case SIMToolkitNegativeACK_caf                          =   1053            // SIMToolkitNegativeACK.caf
                                case SIMToolkitPositiveACK_caf                          =   1054            // SIMToolkitPositiveACK.caf
                                case SIMToolkitSMS_caf                                  =   1055            // SIMToolkitSMS.caf
                                case Tink_caf                                           =   1057            // Tink.caf
        @available(iOS 16.0, *) case WebcamStart_caf                                    =   1060            // WebcamStart.caf
                                case ct_busy_caf                                        =   1070            // ct-busy.caf
                                case ct_congestion_caf                                  =   1071            // ct-congestion.caf
                                case ct_path_ack_caf                                    =   1072            // ct-path-ack.caf
                                case ct_error_caf                                       =   1073            // ct-error.caf
                                case ct_call_waiting_caf                                =   1074            // ct-call-waiting.caf
                                case ct_keytone2_caf                                    =   1075            // ct-keytone2.caf
                                case lock_caf                                           =   1100            // lock.caf
                                case Tink_caf_02                                        =   1103            // Tink.caf
                                case key_press_click_caf                                =   1104            // key_press_click.caf
                                case Tock_caf                                           =   1105            // Tock.caf
                                case connect_power_caf                                  =   1106            // connect_power.caf
                                case RingerChanged_caf                                  =   1107            // RingerChanged.caf
                                case photoShutter_caf                                   =   1108            // photoShutter.caf
                                case shake_caf                                          =   1109            // shake.caf
                                case jbl_begin_caf                                      =   1110            // jbl_begin.caf
                                case jbl_confirm_caf                                    =   1111            // jbl_confirm.caf
                                case jbl_cancel_caf                                     =   1112            // jbl_cancel.caf
                                case begin_record_caf                                   =   1113            // begin_record.caf
                                case end_record_caf                                     =   1114            // end_record.caf
                                case jbl_ambiguous_caf                                  =   1115            // jbl_ambiguous.caf
                                case jbl_no_match_caf                                   =   1116            // jbl_no_match.caf
                                case begin_record_caf_02                                =   1117            // begin_record.caf
                                case end_record_caf_02                                  =   1118            // end_record.caf
                                case camera_shutter_burst_caf                           =   1119            // camera_shutter_burst.caf
        @available(iOS 17.0, *) case airdrop_invite_caf                                 =   1120            // airdrop_invite.caf
                                case camera_shutter_burst_begin_caf                     =   1121            // camera_shutter_burst_begin.caf
                                case camera_shutter_burst_end_caf                       =   1122            // camera_shutter_burst_end.caf
                                case key_press_click_caf_02                             =   1123            // key_press_click.caf
                                case focus_change_keyboard_caf                          =   1124            // focus_change_keyboard.caf
                                case focus_change_app_icon_caf                          =   1125            // focus_change_app_icon.caf
                                case focus_change_large_caf                             =   1126            // focus_change_large.caf
                                case focus_change_small_caf                             =   1127            // focus_change_small.caf
                                case navigation_push_caf                                =   1128            // navigation_push.caf
                                case navigation_pop_caf                                 =   1129            // navigation_pop.caf
                                case keyboard_press_normal_caf                          =   1130            // keyboard_press_normal.caf
                                case keyboard_press_delete_caf                          =   1131            // keyboard_press_delete.caf
                                case keyboard_press_clear_caf                           =   1132            // keyboard_press_clear.caf
                                case vc_invitation_accepted_caf                         =   1150            // vc~invitation-accepted.caf
                                case vc_ringing_caf                                     =   1151            // vc~ringing.caf
                                case vc_ended_caf                                       =   1152            // vc~ended.caf
                                case ct_call_waiting_caf_02                             =   1153            // ct-call-waiting.caf
                                case vc_ringing_caf_02                                  =   1154            // vc~ringing.caf
                                case key_press_delete_caf                               =   1155            // key_press_delete.caf
                                case key_press_modifier_caf                             =   1156            // key_press_modifier.caf
                                case wheels_of_time_caf                                 =   1157            // wheels_of_time.caf
                                case go_to_sleep_alert_caf                              =   1158            // go_to_sleep_alert.caf
                                case warsaw_caf                                         =   1159            // warsaw.caf
                                case nfc_scan_complete_caf                              =   1160            // nfc_scan_complete.caf
                                case access_scan_complete_caf                           =   1163            // access_scan_complete.caf
                                case Third_party_critical_caf                           =   1165            // 3rd_party_critical.caf
                                case PaymentReceived_caf                                =   1166            // PaymentReceived.caf
        @available(iOS 16.0, *) case Doorbell_caf                                       =   1167            // Doorbell.caf
        @available(iOS 16.0, *) case PaymentReceivedFailure_caf                         =   1168            // PaymentReceivedFailure.caf
                                case dtmf_0_caf                                         =   1200            // dtmf-0.caf
                                case dtmf_1_caf                                         =   1201            // dtmf-1.caf
                                case dtmf_2_caf                                         =   1202            // dtmf-2.caf
                                case dtmf_3_caf                                         =   1203            // dtmf-3.caf
                                case dtmf_4_caf                                         =   1204            // dtmf-4.caf
                                case dtmf_5_caf                                         =   1205            // dtmf-5.caf
                                case dtmf_6_caf                                         =   1206            // dtmf-6.caf
                                case dtmf_7_caf                                         =   1207            // dtmf-7.caf
                                case dtmf_8_caf                                         =   1208            // dtmf-8.caf
                                case dtmf_9_caf                                         =   1209            // dtmf-9.caf
                                case dtmf_star_caf                                      =   1210            // dtmf-star.caf
                                case dtmf_pound_caf                                     =   1211            // dtmf-pound.caf
        @available(iOS 16.0, *) case DeviceShutdown_caf                                 =   1253            // DeviceShutdown.caf
                                case long_low_short_high_caf                            =   1254            // long_low_short_high.caf
                                case short_double_high_caf                              =   1255            // short_double_high.caf
                                case short_low_high_caf                                 =   1256            // short_low_high.caf
                                case short_double_low_caf                               =   1257            // short_double_low.caf
                                case short_double_low_caf_02                            =   1258            // short_double_low.caf
                                case middle_9_short_double_low_caf                      =   1259            // middle_9_short_double_low.caf
                                case camera_timer_final_second_caf                      =   1260            // camera_timer_final_second.caf
                                case camera_timer_countdown_caf                         =   1261            // camera_timer_countdown.caf
                                case health_notification_caf                            =   1262            // health_notification.caf
                                case MultiwayJoin_caf                                   =   1263            // MultiwayJoin.caf
                                case MultiwayLeave_caf                                  =   1264            // MultiwayLeave.caf
                                case multiway_invitation_caf                            =   1265            // multiway_invitation.caf
        @available(iOS 16.2, *) case PushToTalkJoined_caf                               =   1270            // PushToTalkJoined.caf
        @available(iOS 16.2, *) case PushToTalkLeft_caf                                 =   1271            // PushToTalkLeft.caf
        @available(iOS 16.2, *) case PushToTalkUnmute_caf                               =   1272            // PushToTalkUnmute.caf
        @available(iOS 16.2, *) case PushToTalkMute_caf                                 =   1273            // PushToTalkMute.caf
        @available(iOS 16.2, *) case PushToTalkUnmuteFail_caf                           =   1274            // PushToTalkUnmuteFail.caf
        @available(iOS 17.0, *) case SenderConfirmation_caf                             =   1275            // SenderConfirmation.caf
        @available(iOS 17.0, *) case ReceiverConfirmation_caf                           =   1276            // ReceiverConfirmation.caf
        @available(iOS 17.0, *) case ReceiverConnect_caf                                =   1277            // ReceiverConnect.caf
                                case sms_received1_caf_05                               =   1300            // sms-received1.caf
                                case ReceivedMessage_caf_02                             =   1301            // ReceivedMessage.caf
                                case new_mail_caf_02                                    =   1302            // new-mail.caf
                                case mail_sent_caf_02                                   =   1303            // mail-sent.caf
                                case alarm_caf_03                                       =   1304            // alarm.caf
                                case lock_caf_02                                        =   1305            // lock.caf
                                case key_press_click_caf_03                             =   1306            // key_press_click.caf
                                case sms_received1_caf_06                               =   1307            // sms-received1.caf
                                case sms_received2_caf_02                               =   1308            // sms-received2.caf
                                case sms_received3_caf_02                               =   1309            // sms-received3.caf
                                case sms_received4_caf_02                               =   1310            // sms-received4.caf
                                case sms_received1_caf_07                               =   1312            // sms-received1.caf
                                case sms_received5_caf_02                               =   1313            // sms-received5.caf
                                case sms_received6_caf_02                               =   1314            // sms-received6.caf
                                case sms_received1_caf_08                               =   1315            // sms-received1.caf
                                case alarm_caf_04                                       =   1317            // alarm.caf
                                case Swish_caf_02                                       =   1318            // Swish.caf
                                case Anticipate_caf_02                                  =   1320            // Anticipate.caf
                                case Bloom_caf_02                                       =   1321            // Bloom.caf
                                case Calypso_caf_02                                     =   1322            // Calypso.caf
                                case Choo_Choo_caf_02                                   =   1323            // Choo_Choo.caf
                                case Descent_caf_02                                     =   1324            // Descent.caf
                                case Fanfare_caf_02                                     =   1325            // Fanfare.caf
                                case Ladder_caf_02                                      =   1326            // Ladder.caf
                                case Minuet_caf_02                                      =   1327            // Minuet.caf
                                case News_Flash_caf_02                                  =   1328            // News_Flash.caf
                                case Noir_caf_02                                        =   1329            // Noir.caf
                                case Sherwood_Forest_caf_02                             =   1330            // Sherwood_Forest.caf
                                case Spell_caf_02                                       =   1331            // Spell.caf
                                case Suspense_caf_02                                    =   1332            // Suspense.caf
                                case Telegraph_caf_02                                   =   1333            // Telegraph.caf
                                case Tiptoes_caf_02                                     =   1334            // Tiptoes.caf
                                case Typewriters_caf_02                                 =   1335            // Typewriters.caf
                                case Update_caf_02                                      =   1336            // Update.caf
        @available(iOS 16.0, *) case PINEnterDigit_AX_caf                               =   1340            // PINEnterDigit_AX.caf
        @available(iOS 16.0, *) case PINDelete_AX_caf                                   =   1341            // PINDelete_AX.caf
        @available(iOS 16.0, *) case PINSubmit_AX_caf                                   =   1342            // PINSubmit_AX.caf
        @available(iOS 16.0, *) case PINUnexpected_caf                                  =   1343            // PINUnexpected.caf
        @available(iOS 16.0, *) case PINEnterDigit_caf                                  =   1344            // PINEnterDigit.caf
        @available(iOS 16.0, *) case PINDelete_caf                                      =   1345            // PINDelete.caf
                                case connect_power_caf_02                               =   1360            // connect_power.caf
                                case connect_power_caf_03                               =   1361            // connect_power.caf
                                case HeadphoneAudioExposureLimitExceeded_caf            =   1362            // HeadphoneAudioExposureLimitExceeded.caf
                                case HealthNotificationUrgent_caf                       =   1363            // HealthNotificationUrgent.caf
                                case MicMute_caf                                        =   1364            // MicMute.caf
                                case MicUnmute_caf                                      =   1365            // MicUnmute.caf
                                case MicUnmuteFail_caf                                  =   1366            // MicUnmuteFail.caf
                                case ScreenSharingStarted_caf                           =   1367            // ScreenSharingStarted.caf
                                case MediaPaused_caf                                    =   1368            // MediaPaused.caf
                                case MediaHandoff_caf                                   =   1369            // MediaHandoff.caf
                                case NavigationGenericManeuver_caf                      =   1370            // NavigationGenericManeuver.caf
                                case ScreenCapture_caf                                  =   1393            // ScreenCapture.caf
                                case payment_success_caf                                =   1394            // payment_success.caf
                                case payment_failure_caf                                =   1395            // payment_failure.caf
                                case acknowledgment_sent_caf                            =   1396            // acknowledgment_sent.caf
                                case acknowledgment_received_caf                        =   1397            // acknowledgment_received.caf
                                case nfc_scan_failure_caf                               =   1398            // nfc_scan_failure.caf
                                case Notification_Haptic_caf                            =   1400            // Notification_Haptic.caf
                                case Ringtone_US_Haptic_caf                             =   1401            // Ringtone_US_Haptic.caf
                                case Ringtone_UK_Haptic_caf                             =   1402            // Ringtone_UK_Haptic.caf
                                case Alarm_Haptic_caf                                   =   1403            // Alarm_Haptic.caf
                                case SiriStart_Haptic_caf                               =   1404            // SiriStart_Haptic.caf
                                case SiriStopSuccess_Haptic_caf                         =   1405            // SiriStopSuccess_Haptic.caf
                                case SiriStopFailure_Haptic_caf                         =   1406            // SiriStopFailure_Haptic.caf
                                case Stockholm_Haptic_caf                               =   1407            // Stockholm_Haptic.caf
                                case Beat_Haptic_caf                                    =   1408            // Beat_Haptic.caf
                                case DoNotDisturb_Haptic_caf                            =   1410            // DoNotDisturb_Haptic.caf
                                case Timer_Haptic_caf                                   =   1413            // Timer_Haptic.caf
                                case NavigationLeftTurn_Haptic_caf                      =   1414            // NavigationLeftTurn_Haptic.caf
                                case NavigationRightTurn_Haptic_caf                     =   1415            // NavigationRightTurn_Haptic.caf
                                case Detent_Haptic_caf                                  =   1416            // Detent_Haptic.caf
                                case NavigationGenericManeuver_Haptic_caf               =   1417            // NavigationGenericManeuver_Haptic.caf
                                case CameraCountdownTick_Haptic_caf                     =   1418            // CameraCountdownTick_Haptic.caf
                                case CameraCountdownImminent_Haptic_caf                 =   1419            // CameraCountdownImminent_Haptic.caf
                                case ET_RemoteTap_Receive_Haptic_caf                    =   1420            // ET_RemoteTap_Receive_Haptic.caf
                                case ET_RemoteTap_Send_Haptic_caf                       =   1421            // ET_RemoteTap_Send_Haptic.caf
                                case ET_BeginNotification_Haptic_caf                    =   1422            // ET_BeginNotification_Haptic.caf
                                case StockholmActive_Haptic_caf                         =   1424            // StockholmActive_Haptic.caf
                                case StockholmActiveSingleCycle_Haptic_caf              =   1425            // StockholmActiveSingleCycle_Haptic.caf
                                case StockholmFailure_Haptic_caf                        =   1426            // StockholmFailure_Haptic.caf
                                case SedentaryTimer_Haptic_caf                          =   1427            // SedentaryTimer_Haptic.caf
                                case HourlyChime_Haptic_caf                             =   1428            // HourlyChime_Haptic.caf
                                case Preview_AudioAndHaptic_caf                         =   1429            // Preview_AudioAndHaptic.caf
                                case Alert_ActivityGoalAttained_Haptic_caf              =   1430            // Alert_ActivityGoalAttained_Haptic.caf
                                case Alert_ActivityGoalBehind_Haptic_caf                =   1431            // Alert_ActivityGoalBehind_Haptic.caf
                                case Alert_ActivityGoalClose_Haptic_caf                 =   1432            // Alert_ActivityGoalClose_Haptic.caf
                                case Alert_BatteryLow_10p_Haptic_caf                    =   1433            // Alert_BatteryLow_10p_Haptic.caf
                                case Alert_BatteryLow_5p_Haptic_caf                     =   1434            // Alert_BatteryLow_5p_Haptic.caf
                                case Alert_Calendar_Haptic_caf                          =   1435            // Alert_Calendar_Haptic.caf
                                case Notification_Haptic_caf_02                         =   1436            // Notification_Haptic.caf
                                case Notification_Haptic_caf_03                         =   1437            // Notification_Haptic.caf
                                case Notification_Haptic_caf_04                         =   1438            // Notification_Haptic.caf
                                case Notification_Haptic_caf_05                         =   1439            // Notification_Haptic.caf
                                case Alert_PassbookBalance_Haptic_caf                   =   1440            // Alert_PassbookBalance_Haptic.caf
                                case Alert_PassbookGeofence_Haptic_caf                  =   1441            // Alert_PassbookGeofence_Haptic.caf
                                case Alert_PhotostreamActivity_Haptic_caf               =   1442            // Alert_PhotostreamActivity_Haptic.caf
                                case Alert_ReminderDue_Haptic_caf                       =   1443            // Alert_ReminderDue_Haptic.caf
                                case Notification_Haptic_caf_06                         =   1444            // Notification_Haptic.caf
                                case Alert_WalkieTalkie_Haptic_caf                      =   1445            // Alert_WalkieTalkie_Haptic.caf
                                case BatteryMagsafe_Haptic_caf                          =   1446            // BatteryMagsafe_Haptic.caf
                                case BuddyPairingFailure_Haptic_caf                     =   1447            // BuddyPairingFailure_Haptic.caf
                                case BuddyPairingSuccess_Haptic_caf                     =   1448            // BuddyPairingSuccess_Haptic.caf
                                case CameraShutter_Haptic_caf                           =   1449            // CameraShutter_Haptic.caf
                                case Alert_MapsDirectionsInApp_Haptic_caf               =   1450            // Alert_MapsDirectionsInApp_Haptic.caf
                                case MessagesIncoming_Haptic_caf                        =   1451            // MessagesIncoming_Haptic.caf
                                case MessagesOutgoing_Haptic_caf                        =   1452            // MessagesOutgoing_Haptic.caf
                                case OnOffPasscodeFailure_Haptic_caf                    =   1453            // OnOffPasscodeFailure_Haptic.caf
                                case OrbLayers_Haptic_caf                               =   1458            // OrbLayers_Haptic.caf
                                case PhoneHangUp_Haptic_caf                             =   1459            // PhoneHangUp_Haptic.caf
                                case PhotosZoomDetent_Haptic_caf                        =   1460            // PhotosZoomDetent_Haptic.caf
                                case QB_Dictation_Haptic_caf                            =   1461            // QB_Dictation_Haptic.caf
                                case StopwatchLap_Haptic_caf                            =   1464            // StopwatchLap_Haptic.caf
                                case StopwatchReset_Haptic_caf                          =   1465            // StopwatchReset_Haptic.caf
                                case StopwatchStart_Haptic_caf                          =   1466            // StopwatchStart_Haptic.caf
                                case StopwatchStop_Haptic_caf                           =   1467            // StopwatchStop_Haptic.caf
                                case TimerCancel_Haptic_caf                             =   1468            // TimerCancel_Haptic.caf
                                case TimerPause_Haptic_caf                              =   1469            // TimerPause_Haptic.caf
                                case TimerStart_Haptic_caf                              =   1470            // TimerStart_Haptic.caf
                                case TimerWheelHoursDetent_Haptic_caf                   =   1471            // TimerWheelHoursDetent_Haptic.caf
                                case WalkieTalkieActiveStart_Haptic_caf                 =   1472            // WalkieTalkieActiveStart_Haptic.caf
                                case WorkoutComplete_Haptic_caf                         =   1473            // WorkoutComplete_Haptic.caf
                                case WorkoutCountdown_Haptic_caf                        =   1474            // WorkoutCountdown_Haptic.caf
                                case Alert_3rdParty_Haptic_caf                          =   1475            // Alert_3rdParty_Haptic.caf
                                case WorkoutSelect_Haptic_caf                           =   1476            // WorkoutSelect_Haptic.caf
                                case WorkoutPressStart_Haptic_caf                       =   1477            // WorkoutPressStart_Haptic.caf
                                case TimerWheelMinutesDetent_Haptic_caf                 =   1479            // TimerWheelMinutesDetent_Haptic.caf
                                case PhoneAnswer_Haptic_caf                             =   1480            // PhoneAnswer_Haptic.caf
                                case PhoneHold_Haptic_caf                               =   1481            // PhoneHold_Haptic.caf
                                case WalkieTalkieActiveEnd_Haptic_caf                   =   1482            // WalkieTalkieActiveEnd_Haptic.caf
                                case UISwitch_On_Haptic_caf                             =   1484            // UISwitch_On_Haptic.caf
                                case UISwitch_Off_Haptic_caf                            =   1485            // UISwitch_Off_Haptic.caf
                                case UISwipe_Haptic_caf                                 =   1486            // UISwipe_Haptic.caf
                                case SystemStartup_Haptic_caf                           =   1487            // SystemStartup_Haptic.caf
                                case BuddyPairingRemoteConnection_Haptic_caf            =   1488            // BuddyPairingRemoteConnection_Haptic.caf
                                case BuddyPairingRemoteTap_Haptic_caf                   =   1489            // BuddyPairingRemoteTap_Haptic.caf
                                case QB_Dictation_Off_Haptic_caf                        =   1490            // QB_Dictation_Off_Haptic.caf
                                case RingtoneDucked_US_Haptic_caf                       =   1491            // RingtoneDucked_US_Haptic.caf
                                case RingtoneDucked_UK_Haptic_caf                       =   1492            // RingtoneDucked_UK_Haptic.caf
                                case SalientNotification_Haptic_caf                     =   1493            // SalientNotification_Haptic.caf
                                case Notification_Salient_Haptic_caf                    =   1494            // Notification_Salient_Haptic.caf
                                case ET_BeginNotification_Salient_Haptic_caf            =   1495            // ET_BeginNotification_Salient_Haptic.caf
                                case Alert_Calendar_Salient_Haptic_caf                  =   1496            // Alert_Calendar_Salient_Haptic.caf
                                case Notification_Salient_Haptic_caf_02                 =   1497            // Notification_Salient_Haptic.caf
                                case Notification_Salient_Haptic_caf_03                 =   1498            // Notification_Salient_Haptic.caf
                                case Alert_ReminderDue_Salient_Haptic_caf               =   1499            // Alert_ReminderDue_Salient_Haptic.caf
                                case Notification_Salient_Haptic_caf_04                 =   1500            // Notification_Salient_Haptic.caf
                                case Alert_3rdParty_Salient_Haptic_caf                  =   1501            // Alert_3rdParty_Salient_Haptic.caf
                                case ThirdParty_DirectionUp_Haptic_caf                  =   1502            // 3rdParty_DirectionUp_Haptic.caf
                                case ThirdParty_DirectionDown_Haptic_caf                =   1503            // 3rdParty_DirectionDown_Haptic.caf
                                case ThirdParty_Success_Haptic_caf                      =   1504            // 3rdParty_Success_Haptic.caf
                                case ThirdParty_Failure_Haptic_caf                      =   1505            // 3rdParty_Failure_Haptic.caf
                                case ThirdParty_Retry_Haptic_caf                        =   1506            // 3rdParty_Retry_Haptic.caf
                                case ThirdParty_Start_Haptic_caf                        =   1507            // 3rdParty_Start_Haptic.caf
                                case ThirdParty_Stop_Haptic_caf                         =   1508            // 3rdParty_Stop_Haptic.caf
                                case Alarm_Nightstand_Haptic_caf                        =   1509            // Alarm_Nightstand_Haptic.caf
                                case Alert_BatteryLow_5p_Salient_Haptic_caf             =   1510            // Alert_BatteryLow_5p_Salient_Haptic.caf
                                case NavigationLeftTurn_Salient_Haptic_caf              =   1511            // NavigationLeftTurn_Salient_Haptic.caf
                                case NavigationRightTurn_Salient_Haptic_caf             =   1512            // NavigationRightTurn_Salient_Haptic.caf
                                case NavigationGenericManeuver_Salient_Haptic_caf       =   1513            // NavigationGenericManeuver_Salient_Haptic.caf
                                case SedentaryTimer_Salient_Haptic_caf                  =   1514            // SedentaryTimer_Salient_Haptic.caf
                                case Alert_ActivityGoalAttained_Salient_Haptic_caf      =   1515            // Alert_ActivityGoalAttained_Salient_Haptic.caf
                                case Alert_ActivityGoalBehind_Salient_Haptic_caf        =   1516            // Alert_ActivityGoalBehind_Salient_Haptic.caf
                                case Alert_PassbookGeofence_Salient_Haptic_caf          =   1517            // Alert_PassbookGeofence_Salient_Haptic.caf
                                case WorkoutSaved_Haptic_caf                            =   1518            // WorkoutSaved_Haptic.caf
                                case VoiceOver_Click_Haptic_caf                         =   1522            // VoiceOver_Click_Haptic.caf
                                case SiriAutoSend_Haptic_caf                            =   1523            // SiriAutoSend_Haptic.caf
                                case HummingbirdCompletion_Haptic_caf                   =   1525            // HummingbirdCompletion_Haptic.caf
                                case HummingbirdNotification_Haptic_caf                 =   1526            // HummingbirdNotification_Haptic.caf
                                case RemoteCameraShutterBurstBegin_Haptic_caf           =   1527            // RemoteCameraShutterBurstBegin_Haptic.caf
                                case RemoteCameraShutterBurstEnd_Haptic_caf             =   1528            // RemoteCameraShutterBurstEnd_Haptic.caf
                                case WorkoutPaused_Haptic_caf                           =   1529            // WorkoutPaused_Haptic.caf
                                case WorkoutResumed_Haptic_caf                          =   1530            // WorkoutResumed_Haptic.caf
                                case GoToSleep_Haptic_caf                               =   1531            // GoToSleep_Haptic.caf
                                case Warsaw_Haptic_caf                                  =   1532            // Warsaw_Haptic.caf
                                case AutoUnlock_Haptic_caf                              =   1533            // AutoUnlock_Haptic.caf
                                case Alert_ActivityFriendsGoalAttained_Haptic_caf       =   1534            // Alert_ActivityFriendsGoalAttained_Haptic.caf
                                case Alert_SpartanConnecting_Haptic_caf                 =   1535            // Alert_SpartanConnecting_Haptic.caf
                                case Alert_SpartanConnecting_LowLatency_Haptic_caf      =   1536            // Alert_SpartanConnecting_LowLatency_Haptic.caf
                                case Alert_SpartanConnected_LowLatency_Haptic_caf       =   1537            // Alert_SpartanConnected_LowLatency_Haptic.caf
                                case Alert_SpartanDisconnected_LowLatency_Haptic_caf_02 =   1538            // Alert_SpartanDisconnected_LowLatency_Haptic.caf
                                case AccessScanComplete_Haptic_caf                      =   1543            // AccessScanComplete_Haptic.caf
                                case BuddyMigrationStart_Haptic_caf                     =   1544            // BuddyMigrationStart_Haptic.caf
                                case SOSFallDetectionPrompt_Haptic_caf                  =   1545            // SOSFallDetectionPrompt_Haptic.caf
                                case SOSEmergencyContactTextPrompt_Haptic_caf           =   1546            // SOSEmergencyContactTextPrompt_Haptic.caf
                                case WorkoutStartAutodetect_caf                         =   1547            // WorkoutStartAutodetect.caf
                                case WorkoutCompleteAutodetect_caf                      =   1548            // WorkoutCompleteAutodetect.caf
                                case WorkoutPausedAutoDetect_caf                        =   1549            // WorkoutPausedAutoDetect.caf
                                case WorkoutResumedAutoDetect_caf                       =   1550            // WorkoutResumedAutoDetect.caf
                                case WorkoutPaceAbove_caf                               =   1551            // WorkoutPaceAbove.caf
                                case WorkoutPaceBelow_caf                               =   1552            // WorkoutPaceBelow.caf
                                case WalkieTalkieReceiveStart_Haptic_caf                =   1553            // WalkieTalkieReceiveStart_Haptic.caf
                                case WalkieTalkieReceiveEnd_Haptic_caf                  =   1554            // WalkieTalkieReceiveEnd_Haptic.caf
                                case Alert_Health_Haptic_caf                            =   1555            // Alert_Health_Haptic.caf
                                case MultiwayJoin_caf_02                                =   1556            // MultiwayJoin.caf
                                case MultiwayLeave_caf_02                               =   1557            // MultiwayLeave.caf
                                case MultiwayInvitation_caf                             =   1558            // MultiwayInvitation.caf
                                case Third_Party_Critical_Haptic_caf                    =   1559            // 3rd_Party_Critical_Haptic.caf
                                case Alert_1stParty_Haptic_caf                          =   1560            // Alert_1stParty_Haptic.caf
                                case HealthNotificationUrgent_caf_02                    =   1561            // HealthNotificationUrgent.caf
        @available(iOS 16.0, *) case Siren_Countdown_Major_Haptic_caf                   =   1563            // Siren_Countdown_Major_Haptic.caf
        @available(iOS 16.0, *) case Siren_Countdown_Minor_Haptic_caf                   =   1564            // Siren_Countdown_Minor_Haptic.caf
        @available(iOS 16.0, *) case Doorbell_Haptic_caf                                =   1566            // Doorbell_Haptic.caf
                                case System_Notification_Haptic_caf                     =   1567            // System_Notification_Haptic.caf
                                case SOSFallDetectionPromptEscalation_Haptic_caf        =   1568            // SOSFallDetectionPromptEscalation_Haptic.caf
                                case HealthReadingComplete_Haptic_caf                   =   1570            // HealthReadingComplete_Haptic.caf
                                case HealthReadingFail_Haptic_caf                       =   1571            // HealthReadingFail_Haptic.caf
                                case HeadphoneAudioExposureLimitExceeded_caf_02         =   1572            // HeadphoneAudioExposureLimitExceeded.caf
                                case ScreenCapture_caf_02                               =   1573            // ScreenCapture.caf
        @available(iOS 16.2, *) case PushToTalkJoined_caf_02                            =   1576            // PushToTalkJoined.caf
        @available(iOS 16.2, *) case PushToTalkLeft_caf_02                              =   1577            // PushToTalkLeft.caf
        @available(iOS 16.2, *) case PushToTalkUnmute_caf_02                            =   1578            // PushToTalkUnmute.caf
        @available(iOS 16.2, *) case PushToTalkMute_caf_02                              =   1579            // PushToTalkMute.caf
        @available(iOS 16.2, *) case PushToTalkUnmuteFail_caf_02                        =   1580            // PushToTalkUnmuteFail.caf
        @available(iOS 17.0, *) case WorkoutPrecisionStart_Haptic_caf                   =   1581            // WorkoutPrecisionStart_Haptic.caf
        @available(iOS 16.2, *) case IntervalEnded_caf                                  =   1582            // IntervalEnded.caf
        @available(iOS 16.2, *) case IntervalUpcoming_caf                               =   1583            // IntervalUpcoming.caf
        @available(iOS 17.0, *) case Elevation_caf                                      =   1584            // Elevation.caf
        @available(iOS 17.0, *) case SenderConfirmation_caf_02                          =   1585            // SenderConfirmation.caf
        @available(iOS 17.0, *) case ReceiverConfirmation_caf_02                        =   1586            // ReceiverConfirmation.caf
        @available(iOS 17.0, *) case ReceiverConnect_caf_02                             =   1587            // ReceiverConnect.caf
        @available(iOS 17.0, *) case SwTest1_Haptic_caf                                 =   3001            // SwTest1_Haptic.caf

                                case Vibration_shortStrong_01                           =   1520
                                case Vibration_shortStrong_02                           =   1011
                                case Vibration_shortWeak_01                             =   1519
                                case Vibration_shortWeak_02                             =   1102
                                case Vibration_shortWeak_03                             =   1521
    }
}
